Add support for Ansys Lab Proxy connection
ansys/pyensight pull request #308
Opened 2023-09-12 18:14 UTC by mfkrogh

Since the web socket server in the EnSight Docker Container is providing an http connection, instead of https which requires a cert, we use an https / http proxy server provided by Ansys Lab for these connections.  When PyEnSight is used with Ansys Lab, it launches the EnSight Docker Container via PyPIM.  PIM handles the details of launching on a back-end VM along with setting up the session-specific proxy server.  The proxy host and port number is passed back to PyEnSight via PyPIM.  Additionally, a session specific GUID is provided that allows the proxy to map multiple session connections to their appropriate container and port.  The GUID is used ether as an http header or as part of the URL query parameters.   All of this is internal and not something a user would manipulate.

The reason this is needed is that some content returned by EnSight over the http connection consists of URLs that the user's browser is intended to access directly, typically through an IFRAME, for example.  Since the browser has no route to the back-end VM server hosting the Docker Container, it must route through the proxy server which is Internet accessible.  The proxy server is acting as a bridge between the browser and the privately hosted http server.  Additionally, since the browser is connecting to something other than 'localhost', it needs to do this over https instead of http as most browsers typically prohibit using http off-box.

2023-09-20 20:01 UTC, mfkrogh commented on src/ansys/pyensight/core/deep_pixel_view.html
deep_pixel_view.html is a template used by renderable.py.  renderable.py replaces 'OPTIONAL_QUERY' with either an empty string or "?instance_name=GUID" and potentially other URL query parameters.

2023-09-26 15:27 UTC, mariostieriansys submitted a review, later dismissed

2023-09-27 12:16 UTC, jerome-blanche requested changes

2023-09-27 12:16 UTC, jerome-blanche commented on src/ansys/pyensight/core/dockerlauncher.py
>              ensight_env_vars = "LD_PRELOAD=/usr/local/lib64/libGL.so.1:/usr/local/lib64/libEGL.so.1"
This should be appended to current value, when not None.
```suggestion
            if ensight_env_vars is None:
                ensight_env_vars = "LD_PRELOAD=/usr/local/lib64/libGL.so.1:/usr/local/lib64/libEGL.so.1"
            else:
                ensight_env_vars += "LD_PRELOAD=/usr/local/lib64/libGL.so.1:/usr/local/lib64/libEGL.so.1"
```

2023-09-27 13:05 UTC, mfkrogh commented
I've retested with Jerome's modifications.  Works well.

2023-09-27 13:12 UTC, mariostieriansys approved these changes

2023-09-27 13:55 UTC, jerome-blanche approved these changes

2023-09-27 14:11 UTC, merged